### ISSUE TITLE
gcc old ，ccmake cannot continue

### ISSUE THREAD

**Issue by huaxueali** [tproffen/DiffuseCode#12]
Hi Thomas！
The version of the server system in our laboratory is too old (rethat6.4) and cannot be connected to the Internet due to a virus. Our gcc version is 4.4.7. During the compilation of the source code package ccmake, the compilation cannot continue due to the gcc version problem. Do you have any suggestions? ,

**Comment by rneder** [comment]
Hi,
the discus suite relies on Fortran 2008 and later, which was released in 2013. Older versions of the gfortan compiler do not include all elements of Fortran2008 and later. 
You could try to edit the file CMakeLists.txt lines 31 to 35 and replace the "4.6" by "4.4" and give it a try. I do not know what error messages you might get. 
If you use the bbb_install_script.sh you will find the file in DIFFUSE_INSTALL/develop/DiffuseCode.
edit, and then try to compile again with:
bbb_install_script.sh install=local code=current
the optional parameter prevent overwriting the current files.
Reinhard Neder

**Comment by pinkutech** [comment]
I am getting errors while running the simul.9.mac with Discus Suite. Can you please suggest me where I am doing wrong? 

The list of errors is as follows: 
___________________________________________________________________ 
***APPL*** Atom number outside limits                    *** -19 ***
***APPL*** Values for 'inc' are wrong                       *** -19 ***
***MAC *** Error in macro line:    15 Level   1          ***
***MAC *** simul.9.mac
***COMM*** Sub menu returned with error                  *** -10 ***
 ***COMM***  Error occured in symmetry menu               *** -10 ***
______________________________________________________________________________
The "simul.9.mac" script is here 

read
cell perow.cell,8,8,8
find env, O, 0,0,0, 0.0,2.0
#
symm
  uvw 0,0,1
  type proper
  angl 10
  trans 0,0,0
  origin 0,0,0
  power 1.
  mode repl
  sel o
  incl env
  run
exit

**Comment by rneder** [comment]
Hi "pinkutech"
the issue at hand is a bug in the symmetry menu that prevents the "inc env" command. I've fixed it and a corrected version will be released soon. 
A work around at the moment would be:
read
cell perow.cell,8,8,8
find env, O, 0,0,0, 0.0,2.0
show env
#
symm
uvw 0,0,1
type proper
angl 10
trans 0,0,0
origin 0,0,0
power 1.
mode repl
sel o
incl env
exit
do LOOP=1, env[0]
symmetry
  incl env[LOOP], env[LOOP]
  run
exit
enddo
show  env


Reinhard Neder
