### ISSUE TITLE
DISCUS giving "Macro not found" error

### ISSUE THREAD

**Issue by njweadock** [tproffen/DiffuseCode#13]
Hi,

I recently installed DISCUS 6.08.02 using WSL and have been working through the Cookbook examples. I have begun to experience an intermittent issue that is difficult to reproduce.

This issue is that I will sometimes try to execute a macro only to have an error arise:
```
suite > @macro, 1,2,3
***MAC*** Macro not found                                              *** -12 ***
```
The macro is in the directory, and shows up with:
```
>system dir
```

This will persist with any of the macros in the directory once the error appears. Sometimes, changing the directory and running macros in the new directory will work. Restarting DISCUS_Suite through ```>exit``` sometimes, but not always, fixes the issue. I can still execute command line commands, but any attempt to call a macro will result in the above error.

I have tried removing any access permissions from the directory, this does not seem to change anything.

I notice that this will also persist if I mistype the name of a macro

**Comment by rneder** [comment]
There should be no comma immediately following the macro name. thus the correct syntax would be:
@macro.mac  1, 2, 3
or
@macro  1, 2, 3  ( provided the macro name is macro.mac
This is the general rule for all DISCUS commands. After the command a white space is required.

Also, please be aware the directory names are case sensitive
