### ISSUE TITLE
make erro /Env Centos7.9 gfortran-7.5.0,hdf5-5.4

### ISSUE THREAD

**Issue by huaxueali** [tproffen/DiffuseCode#14]
Dear developer, I use bbb---.sh or source code package to compile and install on my personal workstation. When I make it, I get the same error! I googled but didn't find the reason for the error, hope you can help me. Greatful!

`[ 37%] Building Fortran object kuplot/prog/CMakeFiles/kuplot_all.dir/kuplot_load_h5.f90.o
/home/bigsybo/Data_centos/Programs/XRD_programs/DISCUS/DiffuseCode-v.6.11.01/kuplot/prog/kuplot_load_h5.f90:5.4:

USE hdf5
    1
Fatal Error: File 'hdf5.mod' opened at (1) is not a GNU Fortran module file
make[2]: *** [kuplot/prog/CMakeFiles/kuplot_all.dir/kuplot_load_h5.f90.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 37%] Building Fortran object diffev/prog/CMakeFiles/diffev_all.dir/diffev_do_exit.f90.o
[ 37%] Building Fortran object diffev/prog/CMakeFiles/diffev_all.dir/compare.f90.o
[ 38%] Building Fortran object diffev/prog/CMakeFiles/diffev_all.dir/initialise.f90.o
[ 38%] Building Fortran object diffev/prog/CMakeFiles/diffev_all.dir/diffev_loop.f90.o
[ 38%] Building Fortran object diffev/prog/CMakeFiles/diffev_all.dir/diffev_upd_par.f90.o
make[1]: *** [kuplot/prog/CMakeFiles/kuplot_all.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
`
`[ 38%] Building Fortran object diffev/prog/CMakeFiles/diffev_all.dir/diffev_set_sub.f90.o
[ 38%] Building Fortran object diffev/prog/CMakeFiles/diffev_all.dir/diffev_add_param.f90.o
[ 39%] Building Fortran object diffev/prog/CMakeFiles/diffev_all.dir/diffev_set_gen.f90.o
[ 39%] Building Fortran object diffev/prog/CMakeFiles/diffev_all.dir/diffev_release.f90.o
[ 39%] Building Fortran object diffev/prog/CMakeFiles/diffev_all.dir/diffev_kdo.f90.o
[ 40%] Linking Fortran static library libdiffev_all.a
[ 40%] Built target diffev_all
make: *** [all] Error 2
`

**Comment by huaxueali** [comment]
I found the reason, because the error caused by the different gcc version I used to compile openmpi has been solved and installed successfully, but now I am facing a new problem that cannot be solved! When I run discuss_suite, it returns: Fortran runtime error: End of record

`[ 99%] Building Fortran object suite/prog/CMakeFiles/discus_suite_full.dir/suite_top.f90.o
/usr/bin/ld: warning: libgfortran.so.4, needed by /usr/local/lib/openmpi-3.1.0-gcc-7.5.0/lib/libmpi_usempif08.so, may conflict with libgfortran.so.3
[ 99%] Built target discus_suite
[100%] Linking Fortran static library libdiscus_suite_full.a
[100%] Built target discus_suite_full
`

`(base) [root@zhansibo DiffuseBuild]# discus_suite 
At line 902 of file /home/bigsybo/Data_centos/Programs/XRD_programs/DISCUS/DiffuseCode-v.6.11.01/lib_f90/appl_unix.f90
Fortran runtime error: End of record
`

**Comment by rneder** [comment]
Dear "huaxueali",
I'm glad to hear that the first issue was fixed. 
The second is a bit strange. Please confirm that the file appl_unix.f90  has 1531 lines of code and that line 902 reads:
   WRITE(line,'(a,I10,a,a)') 'ps -p ',tpid, ' -o comm= > ',temp_file(1:LEN_TRIM(temp_file))
Please continue this at my direct address reinhard.neder@fau.de, I'll place a final comment once the issue is fixed.Please include your time zone, we might run a quick video conference.
Reinhard Neder
