### ISSUE TITLE
Patch file for CMakeLists.txt files when using fort

### ISSUE THREAD

**Issue by sbecuwe** [tproffen/DiffuseCode#15]
I noticed that -openmp is used while it should be -qopenmp for ifort nowadays. 
Please find attached a patch file for version 6.12.03.
[ifort-patch.txt](https://github.com/tproffen/DiffuseCode/files/9631983/ifort-patch.txt)

**Comment by rneder** [comment]
Thank you I've updated my files, will post these onto github shortly
Reinhard Neder

**Comment by sbecuwe** [comment]
It works fine. Thanks!
