### ISSUE TITLE
error compiling discus_exp2pdf_run.f90

### ISSUE THREAD

**Issue by sbecuwe** [tproffen/DiffuseCode#16]
Trying to compile v6.12.03 using ifort 19.1, I get following error:

```
[ 93%] Building Fortran object discus/prog/CMakeFiles/discus_all.dir/discus_exp2pdf_run.f90.o
[...]/DIFFUSE_INSTALL/develop/DiffuseCode/discus/prog/discus_exp2pdf_run.f90(285): error #6406: Conflicting attributes or multiple declaration of name.   [POWDER]
use powder
----^
compilation aborted for [...]/DIFFUSE_INSTALL/develop/DiffuseCode/discus/prog/discus_exp2pdf_run.f90 (code 1)
```

Any suggestion to fix this? Many thanks!

**Comment by rneder** [comment]
Thank you I've updated my files, will post these onto github shortly
Reinhard Neder

**Comment by rneder** [comment]
Sorry, wrong issue. 
At the moment this error is a bit confusing. The ifort error message is short. The name "powder" is certainly unique. It is the same as the source code file but that should not be an issue. Investigating ...

**Comment by rneder** [comment]
Surprisingly the module name "powder" seemed to have been in conflict with the file name "powder.f90" ? 
This is a contradiction to a quick test file and to the behavior of stack.f90 BUT
 Renamed to "module powder_top_mod" in discus_exp2pdf.f90; discus_kdo.f90; discus_reset.f90; powder.f90. Seems to have resolved the issue. Current source code at Github should be OK, new version to come soon
Reinhard Neder

**Comment by sbecuwe** [comment]
It works fine. Thanks!
