### ISSUE TITLE
Installation on arm-architecture

### ISSUE THREAD

**Issue by gitkuy** [tproffen/DiffuseCode#18]
hello, I'm trying to install Discus on a M1 mac book and there seems to be a compilation problem due to the chip-architecture. In particular, it tells me the following:

gfortran  -o pgdemo1 ../src/pgplot/examples/pgdemo1.f -L`pwd` -lpgplot -lpng -lz -L/usr/X11R6/lib -lX11 -L -lgcc -lm -lc
ld: warning: directory not found for option '-L-lgcc'
ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/lib/libc.tbd' for architecture arm64

Do you by chance know a simple fix for this?
Thanks in advance!

**Comment by rneder** [comment]
hello, I've modified the pgplot compilation script. It should now avoid building the pgdemo* files.
on a M1 Mac some of the libraries seem to have been moved to a different location. 
Please try to run the compilation again:
./bbb_install_script_mac.sh
Reinhard Neder

**Comment by gitkuy** [comment]
Dear Reinhard,
thank you for your swift answer!
I tried to install again, however now I seem to have a problem with the Fortran compilation. Here the last lines:
```
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - failed
-- Check for working Fortran compiler: /opt/homebrew/bin/gfortran
-- Check for working Fortran compiler: /opt/homebrew/bin/gfortran - broken
CMake Error at /opt/homebrew/Cellar/cmake/3.25.2/share/cmake/Modules/CMakeTestFortranCompiler.cmake:65 (message):
  The Fortran compiler

    "/opt/homebrew/bin/gfortran"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/moritz/DIFFUSE_INSTALL/develop/DiffuseBuild/CMakeFiles/CMakeScratch/TryCompile-mir9ge
    
    Run Build Command(s):/usr/bin/make -f Makefile cmTC_840c3/fast && /Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/cmTC_840c3.dir/build.make CMakeFiles/cmTC_840c3.dir/build
    Building Fortran object CMakeFiles/cmTC_840c3.dir/testFortranCompiler.f.o
    /opt/homebrew/bin/gfortran   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk -c /Users/moritz/DIFFUSE_INSTALL/develop/DiffuseBuild/CMakeFiles/CMakeScratch/TryCompile-mir9ge/testFortranCompiler.f -o CMakeFiles/cmTC_840c3.dir/testFortranCompiler.f.o
    Linking Fortran executable cmTC_840c3
    /opt/homebrew/Cellar/cmake/3.25.2/bin/cmake -E cmake_link_script CMakeFiles/cmTC_840c3.dir/link.txt --verbose=1
    /opt/homebrew/bin/gfortran  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk CMakeFiles/cmTC_840c3.dir/testFortranCompiler.f.o -o cmTC_840c3 
    ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr/lib/libSystem.tbd' for architecture arm64
    collect2: error: ld returned 1 exit status
    make[1]: *** [cmTC_840c3] Error 1
    make: *** [cmTC_840c3/fast] Error 2
    
  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:6 (enable_language)
```
If I suppress the test compiliation using `set(CMAKE_Fortran_COMPILER_WORKS TRUE)`,  then I arrive at the following:
```
CMake Error at /opt/homebrew/Cellar/cmake/3.25.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenMP_Fortran (missing: OpenMP_Fortran_FLAGS
  OpenMP_Fortran_LIB_NAMES)
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.25.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /opt/homebrew/Cellar/cmake/3.25.2/share/cmake/Modules/FindOpenMP.cmake:580 (find_package_handle_standard_args)
  CMakeLists.txt:71 (find_package)
```
and further up, it still says:
```
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - failed
-- Checking whether /opt/homebrew/bin/gfortran supports Fortran 90
-- Checking whether /opt/homebrew/bin/gfortran supports Fortran 90 - no
status FC set to /opt/homebrew/bin/gfortran 
status TOPLEVEL COMPILER is /opt/homebrew/bin/gfortran
```

**Comment by rneder** [comment]
lovely... On other MAC architectures I'd never had an issue with the compiler... I'll have to read up a bit on MAC ARM etc.., 
Please send me an email to reinhard.neder@fau.de so that we can set up a zoom meeting, might be easier to resolve the issue . Please, also let me know if tomorrow would work out,  I am at Central European time.

**Comment by rneder** [comment]
If Anaconda is active on a MAC the gfortran compiler is messed up during the link stage. 
The installation scripts have been changed to cope with this situation by asking the user to permit a temporary deactivation of conda. It is turned on again once the DISCUS installation is finished.
