### ISSUE TITLE
Kuplot error

### ISSUE THREAD

**Issue by redoxmatlab** [tproffen/DiffuseCode#7]
Hi,
I've installed discus on my mac and while discus seem to work ok, no plotting functionality is working. I have pgplot installed an working and in the PATH. 

I've tried to re-install discus but the error witgh kuplot remains:
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/bin/mixscat
-- Installing: /usr/local/share/mixscat.hlp
-- Up-to-date: /usr/local/share/mixscat/systest.mac
-- Installing: /usr/local/bin/discus
-- Installing: /usr/local/share/discus.hlp
-- Up-to-date: /usr/local/share/color.map
-- Up-to-date: /usr/local/share/discus/systest.mac
-- Installing: /usr/local/bin/diffev
-- Installing: /usr/local/share/diffev.hlp
-- Up-to-date: /usr/local/share/diffev/modify_trial.mac
-- Up-to-date: /usr/local/share/diffev/systest.mac
-- Installing: /usr/local/bin/kuplot
-- Installing: /usr/local/share/kuplot.hlp
CMake Error at kuplot/prog/cmake_install.cmake:66 (file):
  file INSTALL cannot find "//grfont.dat".
Call Stack (most recent call first):
  cmake_install.cmake:36 (include)

make: *** [install] Error 1

Could you please help.
Thanks

**Comment by redoxmatlab** [comment]
declaring the full path seem to have solved the error but plotting functionality still not working.
Here is what I've chnaged in /kuplot/org/cmake_install.cmake:

if("${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share" TYPE FILE FILES "/usr/local/Cellar/pgplot/5.2.2_1/share/grfont.dat")
endif()

if("${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE PROGRAM FILES "/usr/local/Cellar/pgplot/5.2.2_1/bin/pgxwin_server")
endif()

**Comment by tproffen** [comment]
Similar issue - this should not be needed if the PGPLOT environment variables are set correctly in ccmake. Also you need to have a XWindow Server running and MAC stopped installing one by default a few releases ago - sadly I have no Mac to debug this :(

**Comment by redoxmatlab** [comment]
Thanks. I've re-installed discus with pgplot path declared correctly and it seems to work ok now.
Kuplot also work fine using simple xy data but I am getting a strange error with macros similar to the ones in the cook book. 

Please note that the error below has been also replicated both on a LINUX and MAC machines:

Trying, for example, ex_01.mac in chapter 3:

using discus I get:
------ > Waiting for <RETURN> : plot
 discus > #
 discus > rese
 discus > load cr,ex_01.plot
 ***COMM*** Unknown command                               ***  -8 ***

and using kuplot I get:
kuplot > load cr,ex_01.plot
 Reading file ex_01.plot ..
At line 3358 of file /Users/lorentz/CodeHub/Scattering/Diffuse_Discus/DiffuseCode-5.7.0/kuplot/prog/load.f90 (unit = 44, file = 'ex_01.plot')
Fortran runtime error: Bad real number in item 1 of list input

Error termination. Backtrace:
#0  0x11d05cb99
#1  0x11d05d855
#2  0x11d05dfb9
#3  0x11d11d79a
#4  0x11d120c4e
#5  0x101982d97
#6  0x10198666b
#7  0x10196cd40
#8  0x10196e806
#9  0x1019e8136

**Comment by tproffen** [comment]
Ups - we changed the default output format in the plot menu and this creates a CIF file which is not what KUPLOT expects. You will need to add the line 'prog kuplot' to probably all plot*.mac files before the command 'run'.  If I make the change the macros run fine for me.

We will go through the book macros and post an updated version on GitHub hopefully in the next couple of weeks.  

Sorry for the trouble and thanks - Thomas

**Comment by redoxmatlab** [comment]
Thanks, Thomas.
That works very well.
